# Generated by Django 6.0.6 on 2026-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('ASSIGNMENT1', 'Assignment 1'), ('ASSIGNMENT2', 'Assignment 2'), ('CAT1', 'Continuous Assessment Test 1'), ('CAT2', 'Continuous Assessment Test 2'), ('FINAL', 'Final Exam')], max_length=20),
        ),
    ]
